// The purpose of this program is to make a game that allows the user to guess the appropriate key. The correct key will be randomly generated by the program and will change each round. Wins and losses will be stored. Also, the remaining keystrokes will be appropriately displayed

//Problem 1:    Have wins and losses calculated. Losses increases by one if keystroke counter reaches 0. Have wins increase by 1 the correct key is pressed

    //Wins - Increased by 1 if correct key is pressed

var wins = 0;
    //Losses - Increases by 1 if keystroke counter is equal to zero.
var losses = 0;

//Problem 2:    Have a counter that decreases after every keystroke. Resets after 0. Resets if correct key is pressed.

    //Keystroke Counter - If correct key is pressed, keystroke counter resets to 9
    //                      Else keystroke counter decreases by one
var keystrokeCounter = 9;

var keystrokeArray = [];

//Problem 3:    Randomly generated keystroke

    //Put all letters in an array
    //Use math.random to find random letter
    //If keystroke = random letter -> Win!
    //If keystroke != random letter -> Lose!

//Random key generator - Found on Firefox MDN

var minKeyCode = 65;
var maxKeyCode = 90;

var correctKeyCode = getRandomInt(minKeyCode,maxKeyCode)

function getRandomInt(min,max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min)) + min; //The maximum is exclusive and the minimum is inclusive
  }

var correctKeyPress = String.fromCharCode(correctKeyCode)
console.log(correctKeyCode)
console.log(correctKeyPress)

//Initial numbers written to the page

// function getStarted() {
    document.getElementById('winningkey').innerHTML = String.fromCharCode(correctKeyCode);
    document.getElementById('win').innerHTML = wins;
    document.getElementById('keystrokeCount').innerHTML = keystrokeCounter;
    document.getElementById('loss').innerHTML = losses;
// }
//letter event keycodes 65-90

// On keystroke, the key is displayed (addeventlistener)

document.onkeydown = function(event) {
    // getStarted()
    var key_Press = String.fromCharCode(event.keyCode);
    var key_Code = event.keyCode;
    document.getElementById('kp').innerHTML = key_Press;

    
    if (key_Code >= minKeyCode && key_Code <= maxKeyCode) {
        keystrokeArray.push(key_Press);
            // Keystroke Counter

            if (key_Code === correctKeyCode) {
                console.log('validate')
                keystrokeCounter = 9;
                wins = wins + 1;
                keystrokeArray = [];
                correctKeyCode = getRandomInt(minKeyCode,maxKeyCode);
                document.getElementById('winningkey').innerHTML = String.fromCharCode(correctKeyCode);
                document.getElementById('win').innerHTML = wins;
                document.getElementById('keystrokeCount').innerHTML = keystrokeCounter;
            }
            else if (keystrokeCounter === 0) {
                losses = losses + 1;
                keystrokeCounter = 9;
                keystrokeArray = [];
                document.getElementById('loss').innerHTML = losses;
                document.getElementById('keystrokeCount').innerHTML = keystrokeCounter;
            }
            else {
                keystrokeCounter = keystrokeCounter - 1;
                document.getElementById('keystrokeCount').innerHTML = keystrokeCounter;
            }
    }
}
// document.getElementById('keystrokeCount').innerHTML = "9";
// document.getElementById('win').innerHTML = wins;
// document.getElementById('loss').innerHTML = losses;
console.log(keystrokeCounter)
console.log(wins)
console.log(losses)

//If keystrokeCounter = 0, the loss counter will increase

// console.log(key_Press)
// console.log(key_Code)

// Generate Array of Key Strokes



// var userKeyStroke = event.keyCode;

// console.log(userKeyStroke)





//Additional Ideas:
    // Add numbers to the mix