// The purpose of this program is to make a game that allows the user to guess the appropriate key. The correct key will be randomly generated by the program and will change each round. Wins and losses will be stored. Also, the remaining keystrokes will be appropriately displayed

//Problem 1:    Have wins and losses calculated. Losses increases by one if keystroke counter reaches 0. Have wins increase by 1 the correct key is pressed

    //Wins - Increased by 1 if correct key is pressed

var wins = 0;
    //Losses - Increases by 1 if keystroke counter is equal to zero.
var losses = 0;

//Problem 2:    Have a counter that decreases after every keystroke. Resets after 0. Resets if correct key is pressed.

    //Keystroke Counter - If correct key is pressed, keystroke counter resets to 9
    //                      Else keystroke counter decreases by one
var keystrokeCounter = 9;
if (userKeystroke=correctKey) {
    keystrokeCounter = 9;
    wins++;
}
else {
    keystrokeCounter--;
}

//Problem 3:    Randomly generated keystroke

    //Put all letters in an array
    //Use math.random to find random letter
    //If keystroke = random letter -> Win!
    //If keystroke != random letter -> Lose!



//Additional Ideas:
    // Add numbers to the mix